# Generated by Django 4.1.6 on 2023-02-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptId', models.AutoField(primary_key=True, serialize=False)),
                ('DeptName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmpId', models.AutoField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(max_length=50)),
                ('Dept', models.CharField(max_length=50)),
                ('Doj', models.DateField()),
                ('EmpPic', models.CharField(max_length=100)),
            ],
        ),
    ]
